# This is a basic workflow to help you get started with Actions

name: Pull Request Labler

permissions:
  issues: write
  pull-requests: write
  contents: write
  id-token: write
  actions: write
on:
  # Triggers the workflow on pull_request_target request events but only for the "main" branch
  pull_request_target:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ambro-runner-prod
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_BUCKET: ${{ secrets.AWS_BUCKET }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
         ref: ${{ github.event.pull_request.head.sha }}         

      - name: Run Ambro WAF tests
        working-directory: ngx-http-modsecurity/tests
        run: chmod +x ./test.sh && ./test.sh
          
          