name: Ambro Testing On Issues
on:
  issues:
    types:
      - reopened
      - opened
env:
  AWS_ACCOUNT_ID: "556061159831"
  AWS_REGION: "us-east-2"
  ROLE_SESSION_NAME: "ambro-github-actions"
  BUCKET_NAME: "ambro-workflow-docker-prod"
  TEST_CONFIG: "test-parameters-auth"

jobs:
  ambro-testing-on-issue:
    permissions:
      id-token: write
    runs-on: ambro-runner-prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/github-actions/ambro_role_oicd_s3_access
          role-session-name: ${{ env.ROLE_SESSION_NAME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Prepare container for testing
        working-directory: ngx-http-modsecurity/tests
        run: |
          aws s3 cp s3://${{ env.BUCKET_NAME }}/${{ env.TEST_CONFIG }} ${{ env.TEST_CONFIG }}
      
      - name: Run Ambro WAF tests
        working-directory: ngx-http-modsecurity/tests
        run: chmod +x ./test.sh && ./test.sh ${{ env.TEST_CONFIG }}


